# basic options
title: Mojtaba's Blog
author: Mojtaba Tajmohammad
email: tajmohammad40@gmail.com
description: A wonderful blog
github_username:  MojtabaTaj

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
